#!/usr/bin/python3
import matplotlib.pyplot as plt
import numpy as np
import createVectors
import calcZeroGroudPoint

# Data for plotting
end_time = calcZeroGroudPoint.calc_ground_zero_time()
distance = calcZeroGroudPoint.calc_ground_zero_distance(end_time)

t = np.arange(0, end_time, 0.0001)

x = 500*np.cos(np.pi/6)*t
y = 500*np.sin(np.pi/6)*t - (1/2)*9.8*(t**2)

# Create Arrows For Showing Graph Direction
point1Origin = 24
point1Dest = 26
point2Origin = 34
point2Dest = 36

# Create/Plot 2D Curve
fig, ax = plt.subplots()
ax.set(xlabel='x', ylabel='y', title='Problem 55 Section 1.1')
ax.plot(x, y)

# ##Create 1st Direction Arrow
vect1OriginX, vect1OriginY, vect1DestX, vect1DestY = createVectors.create_vector_points(point1Origin, point1Dest)
array = np.array([[vect1OriginX, vect1OriginY, vect1DestX, vect1DestY]])
X, Y, U, V = zip(*array)
ax = plt.gca()
ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

# ##Create 2nd Direction Arrow
vect2OriginX, vect2OriginY, vect2DestX, vect2DestY = createVectors.create_vector_points(point2Origin, point2Dest)
array = np.array([[vect2OriginX, vect2OriginY, vect2DestX, vect2DestY]])
X, Y, U, V = zip(*array)
ax = plt.gca()
ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

ax.grid()

# Center Plot On Valuable Information
# plt.xlim([-1, 25])
# plt.ylim([-9, 5])

plt.show()
