#!/usr/bin/python3
import matplotlib.pyplot as plt
import numpy as np
import createVectors

# Data for plotting
t = np.arange(-2*np.pi, 2*np.pi, 0.0001)

x = t*np.cos(t)
y = t*np.sin(t)

# Create Arrows For Showing Graph Direction
point1Origin = (np.pi/6)
point1Dest = (np.pi/6) + 0.25
point2Origin = 2.50
point2Dest = 2.75

# Create/Plot 2D Curve
fig, ax = plt.subplots()
ax.set(xlabel='x', ylabel='y', title='Problem 59 Section 1.1')
ax.plot(x, y)

# ##Create 1st Direction Arrow
# vect1OriginX, vect1OriginY, vect1DestX, vect1DestY = createVectors.create_vector_points(point1Origin, point1Dest)
# array = np.array([[vect1OriginX, vect1OriginY, vect1DestX, vect1DestY]])
# X, Y, U, V = zip(*array)
# ax = plt.gca()
# ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

# ##Create 2nd Direction Arrow
# vect2OriginX, vect2OriginY, vect2DestX, vect2DestY = createVectors.create_vector_points(point2Origin, point2Dest)
# array = np.array([[vect2OriginX, vect2OriginY, vect2DestX, vect2DestY]])
# X, Y, U, V = zip(*array)
# ax = plt.gca()
# ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

ax.grid()

# Center Plot On Valuable Information
# plt.xlim([-15, 15])
# plt.ylim([-20, 20])

plt.show()
