#!/usr/bin/python3
import matplotlib.pyplot as plt
import numpy as np
import createVectors

# Data for plotting
t = np.arange(0, 12, 0.0001)

x = (1/(np.cos(t)))
y = np.tan(t)

# Create Arrows For Showing Graph Direction
point1Origin = 1.6
point1Dest = 1.65
point2Origin = 4.5
point2Dest = 4.55

# Create/Plot 2D Curve
fig, ax = plt.subplots()
ax.set(xlabel='x', ylabel='y', title='Problem 15 Section 1.1')
ax.plot(x, y)

# ##Create 1st Direction Arrow
# vect1OriginX, vect1OriginY, vect1DestX, vect1DestY = createVectors.create_vector_points(point1Origin, point1Dest)
# array = np.array([[vect1OriginX, vect1OriginY, vect1DestX, vect1DestY]])
# X, Y, U, V = zip(*array)
# ax = plt.gca()
# ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

# ##Create 2nd Direction Arrow
# vect2OriginX, vect2OriginY, vect2DestX, vect2DestY = createVectors.create_vector_points(point2Origin, point2Dest)
# array = np.array([[vect2OriginX, vect2OriginY, vect2DestX, vect2DestY]])
# X, Y, U, V = zip(*array)
# ax = plt.gca()
# ax.quiver(X, Y, U, V, color='steelblue', angles='xy', scale_units='xy', width=0.006, scale=1)

ax.grid()

# Center Plot On Valuable Information
plt.xlim([-6, 6])
plt.ylim([-6, 6])

plt.show()
